### ISSUE TITLE
Use jsx plugin

### ISSUE THREAD

**Issue by guybedford** [tinkertrain/jspm-react#1]
See https://github.com/floatdrop/plugin-jsx.

May be a good alternative to statically compiling.

Transitive source maps will be supported soon.

**Comment by tinkertrain** [comment]
I actually started using it but then switched to jsx compilation with gulp to be able to omit the .jsx extension which doesn't bother me but read somewhere that vim tooling doesn't support it very well (and I don't even use vim). 

Edit: I might switch back to use it anyway as editors and IDE's are incorporating JSX support gradually (sublime, atom, webstorm and brackets for example) and it does simplify the process.

**Comment by guybedford** [comment]
You can use the plugin with any extension with `file.js!jsx`.

It can be nice to let users choose exactly which approach they prefer.

**Comment by jaredly** [comment]
@tinkertrain you can configure vim to tread `jsx` files as javascript just fine - I don't think it's an issue
