### ISSUE TITLE
index.html is not functioning after in production (after "gulp dist")

### ISSUE THREAD

**Issue by zivl** [tinkertrain/jspm-react#11]
hi folks,

Perhaps I am missing something, but here is my problem:
after running `gulp dist` to go on "production mode", all `javascript` files are bundled ok but the index.html there are still references to `jspm_packages` folder and also to some of the JavaScript files as follows:

``` html
   <head>
       <link rel="stylesheet" href="jspm_packages/github/twbs/bootstrap@3.3.4/css/bootstrap.css"/>
       <link rel="stylesheet" href="build/css/main.css"/>
    </head>
    <body>
        <script src="jspm_packages/system.js"></script>
        <script src="config.js"></script> 
        <script>
             System.import('build/js/main.js!jsx');
        </script>
    </body>
```

all those references are no longer exists in dist folder, which is created in the `gulp dist` task. 
Should I configure something to make some adjustments? maybe calling another task to create my own "production mode" html?

**Comment by Robinfr** [comment]
Currently the HTML file is simply directly copied to the dist folder. It would be better to use something like [gulp-htmlbuild](https://www.npmjs.com/package/gulp-htmlbuild).
