### ISSUE TITLE
There is no testing in the tests

### ISSUE THREAD

**Issue by Robinfr** [tinkertrain/jspm-react#12]
There is not actually any testing being done of the React components in the tests. It would very interesting to add this, because this is where most people get stuck.

**Comment by tinkertrain** [comment]
You are right, that'd be great. This kit is a little outdated and lacks stuff like that, atm I don't have spare time to fix it :/

For easier testing of React components, you can have a look at:
- https://github.com/QubitProducts/react-test-tree
- https://github.com/legitcode/tests

Hope that helps!
