### ISSUE TITLE
no hot module replacement

### ISSUE THREAD

**Issue by capaj** [tinkertrain/jspm-react#18]
would it be possible to incclude hot module replacement support as this webpack boilerplate has: https://github.com/gaearon/react-transform-boilerplate

Maybe it could be achieved with: https://github.com/loggur/systemjs-reload
What do you think @tinkertrain ?

**Comment by tinkertrain** [comment]
It definitely would be great, but I haven't tried to implement HMR with jspm before so not sure if it works properly. Unfortunately I have little time to try it out, but if you manage to get it working I'll gladly take a PR!
