### ISSUE TITLE
Upgrade to React 0.13.3?

### ISSUE THREAD

**Issue by mwq27** [tinkertrain/jspm-react#5]
Are there plans to upgrade to the newest version of React?

**Comment by scott-coates** [comment]
I did it in my project and it was fairly easy to do. I'm sure @tinkertrain would welcome a PR :smile:

**Comment by neverfox** [comment]
Not to mention the JSX plugin is deprecated in favor of using Babel.

**Comment by casesandberg** [comment]
This should be closed, react was upgraded here: https://github.com/tinkertrain/jspm-react/commit/292eb8aa47f29c4b1d6f2579dffc41d864be259f
